/* eslint-disable react-refresh/only-export-components */
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

type Language = "ru" | "he";

type TranslationKey = string;

type Dictionary = Record<TranslationKey, string>;

const dictionaries: Record<Language, Dictionary> = {
  ru: {
    "header.deliveryNotice":
      "Доставка по Биробиджану • Заказы на сегодня до 18:00",
    "header.openMenu": "Открыть меню",
    "header.closeMenu": "Закрыть меню",
    "header.homeLabel": "CandyCraft — на главную",
    "header.catalog": "Каталог",
    "header.constructor": "Конструктор",
    "header.delivery": "Доставка и оплата",
    "header.contacts": "Контакты",
    "header.search": "Поиск",
    "header.account": "Аккаунт",
    "header.cart": "Корзина",
    "header.language": "Переключить язык на иврит",
    "authWarn.title": "Вы не авторизованы",
    "authWarn.description": "Авторизуйтесь, чтобы добавлять товары в корзину",
    "authWarn.close": "Закрыть",
    "authWarn.login": "Войти",
    "catalog.allProducts": "Все товары",
    "catalog.searchPlaceholder": "Поиск по каталогу",
    "catalog.searchAria": "Поиск по товарам",
    "catalog.sortAria": "Сортировка товаров",
    "catalog.filters": "Фильтры",
    "catalog.reset": "Сбросить",
    "catalog.inStockOnly": "Только в наличии",
    "catalog.upTo": "До",
    "catalog.emptyTitle": "Ничего не найдено",
    "catalog.emptyDescription": "Попробуйте изменить фильтры или сбросьте их.",
    "catalog.resetFilters": "Сбросить фильтры",
    "catalog.apply": "Применить",
    "catalog.sortPopular": "Сначала популярные",
    "catalog.sortCheap": "Сначала дешевле",
    "catalog.sortExpensive": "Сначала дороже",
    "catalog.sortNew": "Сначала новые",
    "product.noPhoto": "Нет фото",
    "product.category": "Категория",
    "product.outOfStock": "Нет в наличии",
    "product.inStock": "В наличии",
    "product.inCart": "В корзине",
    "product.price": "Цена",
    "product.alreadyInCartAria": "Товар уже в корзине",
    "product.outOfStockAria": "Товара нет в наличии",
    "product.addToCartPrefix": "Добавить",
    "product.addToCartSuffix": "в корзину",
    "product.addToCart": "В корзину",
    "contact.title": "Свяжитесь с нами",
    "contact.badge": "Candy Craft",
    "contact.description":
      "Вопрос, индивидуальный заказ или сотрудничество — напишите, ответим быстро",
    "contact.location": "Локация",
    "contact.locationValue": "Россия",
    "contact.phone": "Телефон",
    "contact.email": "Email",
    "contact.instagram": "Instagram",
    "contact.responseTime": "Время ответа",
    "contact.responseTimeDescription": "Обычно отвечаем в течение 24 часов.",
    "contact.successTitle": "Спасибо! Сообщение отправлено",
    "contact.successDescription": "Мы свяжемся с вами как можно скорее.",
    "contact.sendAnother": "Отправить ещё одно",
    "contact.nameLabel": "Ваше имя",
    "contact.namePlaceholder": "Никита",
    "contact.requiredName": "Введите имя",
    "contact.emailLabel": "Email",
    "contact.requiredEmail": "Введите email",
    "contact.invalidEmail": "Введите корректный email",
    "contact.phoneLabel": "Телефон (опционально)",
    "contact.shortPhone": "Похоже, телефон слишком короткий",
    "contact.messageLabel": "Сообщение",
    "contact.requiredMessage": "Напишите сообщение",
    "contact.messagePlaceholder":
      "Например: хочу торт на день рождения, 19.5 см, на 25 человек...",
    "contact.defaultServerError":
      "Не удалось отправить сообщение. Попробуйте ещё раз.",
    "contact.consentRequired":
      "Необходимо согласие на обработку персональных данных",
    "contact.consentStart":
      "Я согласен на обработку персональных данных для ответа на запрос и ознакомлен с",
    "contact.privacyPolicy": "политикой конфиденциальности",
    "contact.submit": "Отправить",
    "contact.submitting": "Отправляю...",
    "contact.dataNotice": "Данные используются только для обработки обращения.",
    "common.loading": "Загружаем...",
    "notFound.title": "Страница не найдена",
    "notFound.description": "Проверьте адрес или вернитесь в каталог.",
    "notFound.home": "На главную",
    "footer.description":
      "Сладкие подарки и наборы шоколадных тортов, сделанные с заботой.",
    "footer.information": "Информация",
    "footer.privacy": "Политика конфиденциальности",
    "footer.contacts": "Контакты",
    "footer.delivery": "Доставка и оплата",
    "footer.contact": "Связь",
    "footer.email": "Email",
    "footer.phone": "Телефон",
    "footer.rights": "Все права защищены.",
    "delivery.badgeDelivery": "Доставка",
    "delivery.badgePayment": "Оплата",
    "delivery.badgeReturns": "Возврат",
    "delivery.title": "Доставка и оплата",
    "delivery.description":
      "Здесь собрали все важное: сроки, способы доставки, варианты оплаты и ответы на частые вопросы. Если нужна помощь — напишите нам, подскажем.",
    "delivery.catalogCta": "Перейти в каталог",
    "delivery.faqCta": "Частые вопросы",
    "delivery.deliveryTitle": "Доставка",
    "delivery.deliverySubtitle":
      "Доставляем аккуратно, чтобы сладости приехали красивыми и целыми.",
    "delivery.cityCourier": "Курьер по городу",
    "delivery.cityCourierText":
      "Доставка курьером по городу и ближайшим районам. Стоимость и время зависят от адреса.",
    "delivery.landmark": "Ориентир:",
    "delivery.cityCourierHint": "1–3 часа или в удобный интервал.",
    "delivery.pickup": "Самовывоз",
    "delivery.pickupText":
      "Можно забрать заказ самостоятельно по предварительной договоренности.",
    "delivery.important": "Важно:",
    "delivery.pickupHint": "подтвердим время выдачи в сообщениях.",
    "delivery.timing": "Сроки",
    "delivery.timingText":
      "Обычно готовим и отправляем в день заказа или на следующий — зависит от загруженности и наличия.",
    "delivery.timingHint": "Для больших заказов — согласуем заранее.",
    "delivery.packaging": "Упаковка",
    "delivery.packagingText":
      "Упаковываем так, чтобы ничего не помялось: фиксация внутри коробки, защитные слои, аккуратная подача.",
    "delivery.packagingHint": "Можно добавить открытку и пожелание.",
    "delivery.tip": "Совет:",
    "delivery.tipText":
      "если заказ на подарок к точному времени — оформляйте заранее, чтобы мы закрепили слот доставки.",
    "delivery.paymentTitle": "Оплата",
    "delivery.paymentSubtitle":
      "Выберите удобный способ оплаты — быстро и безопасно.",
    "delivery.cardOnline": "Картой онлайн",
    "delivery.cardOnlineText":
      "Оплата банковской картой через безопасный платежный сервис (при наличии в проекте).",
    "delivery.plus": "Плюс:",
    "delivery.cardOnlineHint": "быстрее подтверждение заказа.",
    "delivery.transfer": "Перевод",
    "delivery.transferText":
      "Перевод на карту/счет. Реквизиты отправим после оформления.",
    "delivery.transferHint": "сохраните чек до получения.",
    "delivery.prepaymentText":
      "Для некоторых товаров/дат можем попросить предоплату — это фиксирует бронь и время доставки.",
    "delivery.returnsTitle": "Возврат и замена",
    "delivery.returnsSubtitle":
      "Сладости — товар деликатный, но мы решаем вопросы по-человечески.",
    "delivery.returnsText1":
      "Если вы получили заказ с проблемой (повреждение, ошибка в позиции), напишите нам в течение 2 часов после получения и приложите фото.",
    "delivery.returnsText2":
      "Мы предложим замену/компенсацию в зависимости от ситуации. Для заказов на самовывоз — проверяйте заказ при получении.",
    "delivery.howToOrder": "Как заказать",
    "delivery.step1": "Выберите товары и добавьте в корзину.",
    "delivery.step2": "Оформите заказ и укажите адрес/время.",
    "delivery.step3": "Оплатите удобным способом.",
    "delivery.step4": "Получите заказ — красиво и вовремя.",
    "delivery.cartCta": "Перейти в корзину",
    "delivery.helpTitle": "Нужна помощь?",
    "delivery.helpText":
      "Напишите нам — ответим быстро и поможем оформить заказ.",
    "delivery.phoneLine": "Телефон: +7 (999) 000-00-00",
    "delivery.messengerLine": "WhatsApp/Telegram: @candycraft",
    "delivery.holidayNote":
      "Сроки и стоимость доставки могут меняться в праздничные дни — уточним при оформлении.",
    "delivery.faqTitle": "Частые вопросы",
    "delivery.faqSubtitle":
      "Собрали ответы на самые популярные вопросы по доставке и оплате.",
    "delivery.faq1q": "Можно ли доставить в определенное время?",
    "delivery.faq1a":
      "Да. Укажите желаемый интервал при оформлении — мы подтвердим, если слот свободен. В праздники лучше оформлять заранее.",
    "delivery.faq2q": "Можно ли изменить адрес после оформления?",
    "delivery.faq2a":
      "Можно, если заказ ещё не передан курьеру. Напишите нам как можно быстрее — скорректируем.",
    "delivery.faq3q": "Есть ли доставка в другие города?",
    "delivery.faq3a":
      "Пока работаем в пределах города/районов. Если нужно — напишите, иногда можем согласовать индивидуально.",
    "delivery.faq4q": "Как работает предоплата?",
    "delivery.faq4a":
      "Предоплата фиксирует заказ и время доставки, особенно на популярные даты. Реквизиты пришлём после оформления.",
    "contacts.title": "Контакты",
    "contacts.description":
      "Свяжитесь с нами удобным способом. Мы обычно отвечаем быстро.",
    "contacts.phoneNote": "WhatsApp / звонки",
    "contacts.emailNote": "Для заказов и вопросов",
    "contacts.location": "Локация",
    "contacts.locationValue": "Москва, Россия",
    "contacts.pickupNote": "Самовывоз по договорённости",
    "contacts.hours": "Время работы",
    "contacts.weekdays": "Пн–Пт: 10:00–19:00",
    "contacts.weekend": "Сб–Вс: 11:00–16:00",
    "contacts.howToOrder": "Как заказать",
    "contacts.orderStep1": "Напишите нам в WhatsApp / Telegram или на email.",
    "contacts.orderStep2":
      "Укажите дату, формат набора, бюджет и пожелания по шоколаду.",
    "contacts.orderStep3": "Подтверждаем детали и время получения/доставки.",
    "contacts.fastContact": "Быстрая связь",
    "contacts.fastContactText":
      "Выберите удобный канал связи, отвечаем в течение дня.",
    "contacts.map": "Карта",
    "contacts.mapText":
      "Москва и область. Точный адрес и детали проезда отправим после подтверждения заказа.",
    "contacts.route": "Схема проезда",
    "privacy.back": "Вернуться в каталог",
    "privacy.title": "Политика обработки персональных данных",
    "privacy.updated": "Дата обновления:",
    "privacy.date": "20 июня 2026",
    "privacy.intro":
      "Настоящая политика описывает, какие персональные данные могут обрабатываться на сайте Candy Craft и для каких целей они используются.",
    "privacy.section1": "1. Какие данные обрабатываются",
    "privacy.section1Text": "Сайт может обрабатывать следующие данные:",
    "privacy.itemName": "имя и фамилию;",
    "privacy.itemPhone": "номер телефона;",
    "privacy.itemAddress": "адрес доставки;",
    "privacy.itemOrder": "состав заказа и комментарии к заказу;",
    "privacy.itemTech": "технические данные, необходимые для работы сайта.",
    "privacy.section2": "2. Цели обработки",
    "privacy.section2Text": "Данные используются для:",
    "privacy.purposeAuth": "регистрации и авторизации пользователя;",
    "privacy.purposeOrders": "оформления и обработки заказов;",
    "privacy.purposeContact": "связи с пользователем по заказу или обращению;",
    "privacy.purposeCart": "работы корзины и личного кабинета;",
    "privacy.purposeSecurity": "обеспечения безопасности сайта.",
    "privacy.section3": "3. Передача данных третьим лицам",
    "privacy.section3Text":
      "Данные могут передаваться только в случаях, необходимых для работы сайта и исполнения заказа, например платежному провайдеру или службе доставки. Данные не продаются и не передаются для сторонней рекламы.",
    "privacy.section4": "4. Cookies",
    "privacy.section4Text":
      "Сайт использует cookies и аналогичные технические механизмы для авторизации, поддержания сессии пользователя, работы корзины и обеспечения безопасности.",
    "privacy.section5": "5. Хранение и защита данных",
    "privacy.section5Text":
      "Данные хранятся в информационной системе сайта и используются только в объеме, необходимом для работы сервиса. Пароли пользователей не хранятся в открытом виде.",
    "privacy.section6": "6. Права пользователя",
    "privacy.section6Text": "Пользователь может запросить:",
    "privacy.rightsClarify": "уточнение своих данных;",
    "privacy.rightsDelete": "удаление аккаунта или отдельных данных;",
    "privacy.rightsInfo": "информацию о целях обработки данных.",
    "privacy.section7": "7. Контакты",
    "privacy.section7Text":
      "По вопросам обработки персональных данных можно написать на email:",
    "privacy.continue": "Продолжить покупки",
    "privacy.emailCta": "Написать на email",
    "productPage.loading": "Загрузка товара...",
    "productPage.notFound": "Товар не найден",
    "productPage.notFoundDescription":
      "Извините, запрашиваемый товар не существует или был удалён",
    "productPage.backCatalog": "Вернуться в каталог",
    "productPage.home": "Главная",
    "productPage.back": "← Назад",
    "productInfo.pieces": "шт",
    "productInfo.total": "Итого:",
    "productInfo.add": "Добавить в корзину",
    "productInfo.categoryLabel": "Категория:",
    "productInfo.categoryValue": "Конфетные торты",
    "productInfo.weightLabel": "Вес:",
    "productInfo.weightValue": "Индивидуально по составу",
    "productInfo.compositionLabel": "Состав:",
    "productInfo.compositionValue":
      "Конфеты, шоколад, упаковка и декоративная основа",
    "cart.title": "Корзина покупок",
    "cart.emptyTitle": "Корзина пуста",
    "cart.emptyDescription":
      "Добавьте товары из каталога, чтобы начать покупки",
    "cart.catalogCta": "Перейти в каталог",
    "cart.customBuild": "Индивидуальная сборка",
    "cart.available": "Доступно",
    "cart.innerMissing": "внутренний слой не указан",
    "cart.noDecor": "без декора",
    "cart.inscription": "надпись",
    "cart.candies": "конфет",
    "cart.decrease": "Уменьшить",
    "cart.increase": "Увеличить",
    "cart.remove": "Удалить товар",
    "cart.summaryTitle": "Итоговая сумма",
    "cart.items": "Товары",
    "cart.discount": "Скидка",
    "cart.payTotal": "Итого к оплате",
    "cart.checkout": "Оформить заказ",
    "cart.freeDelivery": "Бесплатная доставка от 6000 ₽",
    "cart.shape.round": "круг",
    "cart.shape.square": "квадрат",
    "cart.shape.heart": "сердце",
    "cart.size.small": "малый",
    "cart.size.medium": "средний",
    "cart.size.large": "большой",
    "cart.color.pink": "розовый",
    "cart.color.gold": "золотой",
    "cart.color.white": "белый",
    "cart.decor.none": "без декора",
    "cart.decor.flowers": "цветы",
    "cart.decor.bow": "бант",
    "cart.decor.topper": "топпер с надписью",
    "cart.packaging.standard": "фирменная коробка",
    "cart.packaging.window": "коробка с окном",
    "cart.packaging.gift": "подарочная упаковка",
    "cart.packaging.premium": "премиум-бокс",
    "auth.shellAccount": "sweet account",
    "auth.benefitFast": "✅ Быстрое оформление заказа",
    "auth.benefitHistory": "✅ История “сладких” покупок",
    "auth.benefitRepeat": "✅ Повтор заказа в 1 клик",
    "auth.tagline": "Candy Craft — торты из любимых шоколадок.",
    "auth.emailInvalid": "Некорректный email",
    "auth.passwordRequired": "Введите пароль",
    "auth.passwordMin": "Минимум 6 символов",
    "auth.loginFallback": "Не удалось войти",
    "auth.loginTitle": "С возвращением",
    "auth.loginSubtitle":
      "Войдите, чтобы быстрее оформлять заказы и отслеживать доставку.",
    "auth.noAccount": "Нет аккаунта?",
    "auth.registerLink": "Зарегистрироваться",
    "auth.google": "Войти через Google",
    "auth.yandex": "Войти через Яндекс",
    "auth.vk": "Войти через VK",
    "auth.emailPlaceholder": "куда отправлять чек",
    "auth.password": "Пароль",
    "auth.forgot": "Забыли пароль?",
    "auth.passwordPlaceholder": "секретный ингредиент",
    "auth.hide": "Скрыть",
    "auth.show": "Показать",
    "auth.loginButton": "Войти",
    "auth.loggingIn": "Вхожу...",
    "auth.lastNameRequired": "Введите фамилию",
    "auth.confirmPasswordRequired": "Повторите пароль",
    "auth.passwordMismatch": "Пароли не совпадают",
    "auth.accountCreated": "Аккаунт создан. Теперь можно войти.",
    "auth.registerFallback": "Не удалось зарегистрироваться",
    "auth.registerTitle": "Создадим аккаунт",
    "auth.registerSubtitle": "Пара секунд — и ваш Candy Craft профиль готов.",
    "auth.hasAccount": "Уже есть аккаунт?",
    "auth.firstName": "Имя",
    "auth.firstNamePlaceholder": "как к вам обращаться",
    "auth.lastName": "Фамилия",
    "auth.lastNamePlaceholder": "для доставки",
    "auth.phone": "Телефон",
    "auth.optional": "(необязательно)",
    "auth.confirmPassword": "Повтор пароля",
    "auth.confirmPasswordPlaceholder": "ещё раз, чтобы точно",
    "auth.consentStart":
      "Я согласен на обработку персональных данных и ознакомлен с",
    "auth.registerButton": "Зарегистрироваться",
    "auth.registering": "Создаю аккаунт...",
    "account.loadProfileError": "Не удалось загрузить профиль",
    "account.loadOrdersError": "Не удалось загрузить заказы",
    "account.fillName": "Заполните имя и фамилию",
    "account.checkEmail": "Проверьте email",
    "account.phoneFormat": "Введите телефон в формате +7 (999) 999-99-99",
    "account.saved": "Сохранено",
    "account.saveError": "Не удалось сохранить",
    "account.title": "Личный кабинет",
    "account.helloPrefix": "Привет,",
    "account.helloSuffix": "Здесь — профиль и ваши заказы.",
    "account.admin": "В админку",
    "account.logout": "Выйти",
    "account.profile": "Профиль",
    "account.orders": "Заказы",
    "account.profileData": "Данные профиля",
    "account.profileHint": "Обновите контакты для уведомлений по заказам",
    "account.phoneRu": "Телефон (РФ)",
    "account.phoneRequired": "Обязателен для связи по заказу.",
    "account.saving": "Сохраняю...",
    "account.save": "Сохранить",
    "account.myOrders": "Мои заказы",
    "account.newOrder": "Сделать новый заказ",
    "account.noOrders": "Пока нет заказов. Самое время собрать сладкий шедевр",
    "account.number": "№",
    "account.date": "Дата",
    "account.status": "Статус",
    "account.amount": "Сумма",
    "account.detailsSoon": "скоро “детали”",
    "account.statusAuto":
      "Статусы обновляются автоматически, когда заказ меняет этап.",
    "account.status.PENDING": "Создан",
    "account.status.PAID": "Оплачен",
    "account.status.PROCESSING": "Готовим",
    "account.status.SHIPPED": "Отправлен",
    "account.status.COMPLETED": "Выполнен",
    "account.status.CANCELED": "Отменён",
    "checkout.selectDelivery": "Выберите способ доставки",
    "checkout.loginRequired": "Нужно войти в аккаунт перед оплатой",
    "checkout.emptyCart": "Корзина пуста",
    "checkout.paymentLinkMissing":
      "Платеж создан, но ссылка на оплату не получена",
    "checkout.createError": "Не удалось создать заказ/платеж",
    "checkout.successTitle": "🎉 Заказ создан!",
    "checkout.successText":
      "Ваша волшебная коробка конфет уже собирается нашими кондитерами!",
    "checkout.orderNumber": "Номер заказа:",
    "checkout.courierCall":
      "Ожидайте звонка от нашего курьера в течение 30 минут",
    "checkout.delivery": "Доставка",
    "checkout.assembly": "Сборка",
    "checkout.assemblyNow": "Начинается сейчас",
    "checkout.sms": "СМС уведомление",
    "checkout.sentTo": "Отправили на",
    "checkout.backShop": "Вернуться в магазин",
    "checkout.backCart": "Назад к корзине",
    "checkout.title": "Оформление заказа",
    "checkout.step": "Шаг",
    "checkout.of": "из",
    "checkout.step1": "Контактные данные",
    "checkout.step2": "Способ доставки",
    "checkout.step3": "Дополнительные опции",
    "checkout.step4": "Подтверждение",
    "checkout.productsCount": "товаров",
    "checkout.back": "Назад",
    "checkout.continue": "Продолжить",
    "checkout.consentStart":
      "Я согласен на обработку персональных данных для оформления заказа и ознакомлен с",
    "checkout.processing": "Оформляем...",
    "checkout.finish": "Завершить заказ",
    "checkout.total": "Итого:",
    "checkout.addressTitle": "Адрес доставки",
    "checkout.addressSubtitle": "Расскажите, куда доставить сладости",
    "checkout.savedAddresses": "Сохранённые адреса",
    "checkout.selectAddress": "Выберите адрес",
    "checkout.address": "Адрес",
    "checkout.deliveryMethodTitle": "Способ доставки",
    "checkout.deliveryMethodSubtitle": "Как быстро хотите получить сладости?",
    "checkout.deliveryLoadError": "Не удалось загрузить способы доставки",
    "checkout.optionsTitle": "Дополнительные опции",
    "checkout.optionsSubtitle": "Добавьте магии в вашу коробку сладостей",
    "checkout.optionsLoadError": "Не удалось загрузить дополнительные опции",
    "checkout.noteLabel": "Ваши пожелания к заказу",
    "checkout.notePlaceholder":
      "Напишите здесь ваши пожелания, аллергии, особые указания...",
    "checkout.reviewTitle": "Проверьте заказ",
    "checkout.reviewSubtitle": "Убедитесь, что всё верно перед оформлением",
    "checkout.yourBox": "🍬 Ваша коробка конфет 🍬",
    "checkout.orderContents": "Содержимое заказа",
    "checkout.customCake": "Индивидуальный торт",
    "checkout.customCandyCake": "Индивидуальный конфетный торт",
    "checkout.extraOptions": "Доп. опции:",
    "checkout.summary": "Итоговая сумма",
    "checkout.products": "Товары:",
    "payment.status.SUCCEEDED": "Оплата прошла успешно",
    "payment.status.PENDING": "Платеж создается",
    "payment.status.WAITING_FOR_CAPTURE": "Платеж ожидает подтверждения",
    "payment.status.CANCELED": "Платеж отменен",
    "payment.status.FAILED": "Ошибка оплаты",
    "payment.invalidOrder": "Некорректный номер заказа",
    "payment.loadError": "Не удалось получить статус оплаты",
    "payment.title": "Результат оплаты",
    "payment.checking": "Проверяем статус...",
    "payment.order": "Заказ:",
    "payment.amount": "Сумма:",
    "payment.statusLabel": "Статус:",
    "payment.notFound": "Платеж пока не найден для заказа",
    "payment.account": "В личный кабинет",
    "payment.catalog": "В каталог",
    "address.placeholder": "Город, улица, дом",
    "address.searching": "Поиск адреса...",
    "cake.backCatalog": "Вернуться в каталог",
    "cake.badge": "Пошаговый конструктор",
    "cake.heroTitle": "Соберите торт по этапам",
    "cake.heroText":
      "Сначала задайте размер и форму, затем наружный ряд конфет, внутренний слой, декор и упаковку. Итоговая стоимость обновляется на каждом шаге.",
    "cake.stepSize": "Размер",
    "cake.stepSizeCaption": "Форма и габарит торта",
    "cake.stepOuter": "Наружный ряд",
    "cake.stepOuterCaption": "Конфеты по борту и цвет ленты",
    "cake.stepInner": "Внутренний слой",
    "cake.stepInnerCaption": "Конфеты внутри сборки",
    "cake.stepDecor": "Декор",
    "cake.stepDecorCaption": "Детали и надпись",
    "cake.stepPackaging": "Упаковка",
    "cake.stepPackagingCaption": "Финальная подача",
    "cake.loginRequired": "Войдите в аккаунт, чтобы добавить торт в корзину",
    "cake.addError": "Не удалось добавить торт в корзину",
    "cake.chooseSize": "Выберите размер",
    "cake.chooseShape": "Выберите форму",
    "cake.outerCandies": "Наружный ряд конфет",
    "cake.ribbonColor": "Цвет ленты и акцентов",
    "cake.inscription": "Надпись",
    "cake.inscriptionPlaceholder": "Например: С днём рождения",
    "cake.inscriptionHint": "До 40 символов, надпись попадёт в макет и заказ.",
    "cake.stage": "Этап",
    "cake.checkSummary": "Проверьте итог и количество в блоке справа.",
    "cake.next": "Далее",
    "cake.summaryStep": "Шаг 5",
    "cake.summaryTitle": "Итог",
    "cake.shape": "Форма",
    "cake.notSet": "Не задан",
    "cake.color": "Цвет",
    "cake.quantity": "Количество",
    "cake.adding": "Добавляем...",
    "cake.addToCart": "Добавить в корзину",
    "cake.selectedCandies": "Выбранные конфеты и проценты",
    "cake.pickCandy": "Выберите хотя бы одну конфету.",
    "cake.percentSum": "Сумма процентов",
    "cake.percentError":
      "Сумма процентов должна быть ровно 100%. Иначе перейти дальше нельзя.",
    "cake.innerLayerPrice": "Стоимость внутреннего слоя",
    "cake.compositionEmpty": "Состав пока не задан.",
    "cake.innerPriceHint":
      "Стоимость рассчитана по выбранным процентам и размеру торта.",
    "cake.option.base.round.label": "Круглый торт",
    "cake.option.base.round.description": "Классическая форма",
    "cake.option.base.heart.label": "Сердце",
    "cake.option.base.heart.description": "Подарочный акцент",
    "cake.option.base.square.label": "Квадратный торт",
    "cake.option.base.square.description": "Ровная современная форма",
    "cake.option.color.pink.label": "Розовый",
    "cake.option.color.gold.label": "Золото",
    "cake.option.color.white.label": "Белый",
    "cake.option.wrapper.satin.label": "Атласная лента",
    "cake.option.wrapper.satin.description": "Классическая лента вокруг торта",
    "cake.option.wrapper.lace.label": "Кружевная обёртка",
    "cake.option.wrapper.lace.description": "Нежная фактурная отделка по борту",
    "cake.option.wrapper.kraft.label": "Крафт-бортик",
    "cake.option.wrapper.kraft.description": "Спокойная натуральная подача",
    "cake.option.wrapper.transparent.label": "Прозрачный борт",
    "cake.option.wrapper.transparent.description": "Акцент на видимые конфеты",
    "cake.option.packaging.standard.label": "Фирменная коробка",
    "cake.option.packaging.standard.description": "Белая коробка CandyCraft",
    "cake.option.packaging.window.label": "Коробка с окном",
    "cake.option.packaging.window.description": "Торт виден до открытия",
    "cake.option.packaging.gift.label": "Подарочная упаковка",
    "cake.option.packaging.gift.description":
      "Бант, бирка и праздничная подача",
    "cake.option.decor.bow.label": "Бант",
    "cake.option.decor.bow.description": "Декоративный бант на торте",
    "cake.option.decor.topper.label": "Топпер с надписью",
    "cake.option.decor.topper.description": "Верхний топпер с вашим текстом",
    "cake.noDecor": "Без декора",
  },
  he: {
    "header.deliveryNotice": "משלוחים בבירוביג'ן • הזמנות להיום עד 18:00",
    "header.openMenu": "פתח תפריט",
    "header.closeMenu": "סגור תפריט",
    "header.homeLabel": "CandyCraft - לעמוד הראשי",
    "header.catalog": "קטלוג",
    "header.constructor": "בונה עוגות",
    "header.delivery": "משלוח ותשלום",
    "header.contacts": "יצירת קשר",
    "header.search": "חיפוש",
    "header.account": "חשבון",
    "header.cart": "עגלה",
    "header.language": "החלף שפה לרוסית",
    "authWarn.title": "אינך מחובר",
    "authWarn.description": "התחבר כדי להוסיף מוצרים לעגלה",
    "authWarn.close": "סגור",
    "authWarn.login": "כניסה",
    "catalog.allProducts": "כל המוצרים",
    "catalog.searchPlaceholder": "חיפוש בקטלוג",
    "catalog.searchAria": "חיפוש מוצרים",
    "catalog.sortAria": "מיון מוצרים",
    "catalog.filters": "מסננים",
    "catalog.reset": "איפוס",
    "catalog.inStockOnly": "רק במלאי",
    "catalog.upTo": "עד",
    "catalog.emptyTitle": "לא נמצאו מוצרים",
    "catalog.emptyDescription": "נסו לשנות את המסננים או לאפס אותם.",
    "catalog.resetFilters": "אפס מסננים",
    "catalog.apply": "החל",
    "catalog.sortPopular": "הפופולריים קודם",
    "catalog.sortCheap": "הזולים קודם",
    "catalog.sortExpensive": "היקרים קודם",
    "catalog.sortNew": "החדשים קודם",
    "product.noPhoto": "אין תמונה",
    "product.category": "קטגוריה",
    "product.outOfStock": "אזל מהמלאי",
    "product.inStock": "במלאי",
    "product.inCart": "בעגלה",
    "product.price": "מחיר",
    "product.alreadyInCartAria": "המוצר כבר בעגלה",
    "product.outOfStockAria": "המוצר אינו במלאי",
    "product.addToCartPrefix": "הוסף את",
    "product.addToCartSuffix": "לעגלה",
    "product.addToCart": "לעגלה",
    "contact.title": "צרו איתנו קשר",
    "contact.badge": "Candy Craft",
    "contact.description":
      "שאלה, הזמנה אישית או שיתוף פעולה? כתבו לנו ונחזור במהירות",
    "contact.location": "מיקום",
    "contact.locationValue": "רוסיה",
    "contact.phone": "טלפון",
    "contact.email": "אימייל",
    "contact.instagram": "אינסטגרם",
    "contact.responseTime": "זמן מענה",
    "contact.responseTimeDescription": "בדרך כלל אנחנו עונים בתוך 24 שעות.",
    "contact.successTitle": "תודה! ההודעה נשלחה",
    "contact.successDescription": "ניצור איתך קשר בהקדם האפשרי.",
    "contact.sendAnother": "שליחת הודעה נוספת",
    "contact.nameLabel": "השם שלך",
    "contact.namePlaceholder": "שם",
    "contact.requiredName": "יש להזין שם",
    "contact.emailLabel": "אימייל",
    "contact.requiredEmail": "יש להזין אימייל",
    "contact.invalidEmail": "יש להזין אימייל תקין",
    "contact.phoneLabel": "טלפון (אופציונלי)",
    "contact.shortPhone": "נראה שמספר הטלפון קצר מדי",
    "contact.messageLabel": "הודעה",
    "contact.requiredMessage": "יש לכתוב הודעה",
    "contact.messagePlaceholder":
      "לדוגמה: אני רוצה עוגת יום הולדת, 19.5 ס״מ, ל-25 אנשים...",
    "contact.defaultServerError": "לא הצלחנו לשלוח את ההודעה. נסו שוב.",
    "contact.consentRequired": "נדרשת הסכמה לעיבוד נתונים אישיים",
    "contact.consentStart":
      "אני מסכים/ה לעיבוד נתונים אישיים לצורך מענה לפנייה וקראתי את",
    "contact.privacyPolicy": "מדיניות הפרטיות",
    "contact.submit": "שליחה",
    "contact.submitting": "שולח...",
    "contact.dataNotice": "הנתונים משמשים רק לטיפול בפנייה.",
    "common.loading": "טוען...",
    "notFound.title": "העמוד לא נמצא",
    "notFound.description": "בדקו את הכתובת או חזרו לקטלוג.",
    "notFound.home": "לעמוד הראשי",
    "footer.description": "מתנות מתוקות וערכות עוגות שוקולד שנעשות באהבה.",
    "footer.information": "מידע",
    "footer.privacy": "מדיניות פרטיות",
    "footer.contacts": "יצירת קשר",
    "footer.delivery": "משלוח ותשלום",
    "footer.contact": "פרטי קשר",
    "footer.email": "אימייל",
    "footer.phone": "טלפון",
    "footer.rights": "כל הזכויות שמורות.",
    "delivery.badgeDelivery": "משלוח",
    "delivery.badgePayment": "תשלום",
    "delivery.badgeReturns": "החזרות",
    "delivery.title": "משלוח ותשלום",
    "delivery.description":
      "כאן ריכזנו את כל המידע החשוב: זמני הכנה, אפשרויות משלוח, דרכי תשלום ותשובות לשאלות נפוצות. צריכים עזרה? כתבו לנו ונעזור.",
    "delivery.catalogCta": "מעבר לקטלוג",
    "delivery.faqCta": "שאלות נפוצות",
    "delivery.deliveryTitle": "משלוח",
    "delivery.deliverySubtitle":
      "אנחנו מוסרים בזהירות כדי שהמתוקים יגיעו יפים ושלמים.",
    "delivery.cityCourier": "שליח בעיר",
    "delivery.cityCourierText":
      "משלוח עם שליח בעיר ובאזורים קרובים. העלות והזמן תלויים בכתובת.",
    "delivery.landmark": "הערכה:",
    "delivery.cityCourierHint": "1–3 שעות או בטווח שנוח לכם.",
    "delivery.pickup": "איסוף עצמי",
    "delivery.pickupText": "אפשר לאסוף את ההזמנה בתיאום מראש.",
    "delivery.important": "חשוב:",
    "delivery.pickupHint": "נאשר את שעת האיסוף בהודעות.",
    "delivery.timing": "זמנים",
    "delivery.timingText":
      "בדרך כלל מכינים ושולחים ביום ההזמנה או למחרת, בהתאם לעומס ולזמינות.",
    "delivery.timingHint": "להזמנות גדולות נתאם מראש.",
    "delivery.packaging": "אריזה",
    "delivery.packagingText":
      "אנחנו אורזים כך שהכול יישאר שלם: קיבוע בתוך הקופסה, שכבות הגנה והגשה נקייה.",
    "delivery.packagingHint": "אפשר להוסיף כרטיס ברכה והקדשה.",
    "delivery.tip": "טיפ:",
    "delivery.tipText":
      "אם ההזמנה היא מתנה לשעה מדויקת, הזמינו מראש כדי שנשמור לכם חלון משלוח.",
    "delivery.paymentTitle": "תשלום",
    "delivery.paymentSubtitle": "בחרו דרך תשלום נוחה, מהירה ובטוחה.",
    "delivery.cardOnline": "כרטיס אונליין",
    "delivery.cardOnlineText":
      "תשלום בכרטיס בנק דרך שירות תשלום מאובטח, אם פעיל בפרויקט.",
    "delivery.plus": "יתרון:",
    "delivery.cardOnlineHint": "אישור הזמנה מהיר יותר.",
    "delivery.transfer": "העברה",
    "delivery.transferText": "העברה לכרטיס/חשבון. נשלח פרטים לאחר ההזמנה.",
    "delivery.transferHint": "שמרו את הקבלה עד קבלת ההזמנה.",
    "delivery.prepaymentText":
      "בחלק מהמוצרים או התאריכים ייתכן שנבקש מקדמה, כדי לשמור את ההזמנה ואת זמן המשלוח.",
    "delivery.returnsTitle": "החזרות והחלפה",
    "delivery.returnsSubtitle":
      "מתוקים הם מוצר עדין, אבל אנחנו פותרים בעיות בצורה הוגנת.",
    "delivery.returnsText1":
      "אם קיבלתם הזמנה עם בעיה (נזק או טעות בפריט), כתבו לנו בתוך שעתיים מקבלת ההזמנה וצרפו תמונה.",
    "delivery.returnsText2":
      "נציע החלפה או פיצוי בהתאם למקרה. באיסוף עצמי, בדקו את ההזמנה בעת הקבלה.",
    "delivery.howToOrder": "איך מזמינים",
    "delivery.step1": "בחרו מוצרים והוסיפו לעגלה.",
    "delivery.step2": "השלימו הזמנה וציינו כתובת/שעה.",
    "delivery.step3": "שלמו בדרך שנוחה לכם.",
    "delivery.step4": "קבלו את ההזמנה יפה ובזמן.",
    "delivery.cartCta": "מעבר לעגלה",
    "delivery.helpTitle": "צריכים עזרה?",
    "delivery.helpText": "כתבו לנו, נענה במהירות ונעזור לבצע הזמנה.",
    "delivery.phoneLine": "טלפון: +7 (999) 000-00-00",
    "delivery.messengerLine": "WhatsApp/Telegram: @candycraft",
    "delivery.holidayNote":
      "זמני ועלויות המשלוח עשויים להשתנות בחגים, נעדכן בעת ההזמנה.",
    "delivery.faqTitle": "שאלות נפוצות",
    "delivery.faqSubtitle": "אספנו תשובות לשאלות נפוצות על משלוח ותשלום.",
    "delivery.faq1q": "אפשר לקבל משלוח בשעה מסוימת?",
    "delivery.faq1a":
      "כן. ציינו את הטווח הרצוי בעת ההזמנה ונאשר אם החלון פנוי. בחגים כדאי להזמין מראש.",
    "delivery.faq2q": "אפשר לשנות כתובת אחרי ההזמנה?",
    "delivery.faq2a":
      "אפשר, אם ההזמנה עדיין לא נמסרה לשליח. כתבו לנו בהקדם ונעדכן.",
    "delivery.faq3q": "יש משלוח לערים אחרות?",
    "delivery.faq3a":
      "כרגע עובדים בעיר ובאזורים קרובים. אם צריך, כתבו לנו ולעיתים נוכל לתאם אישית.",
    "delivery.faq4q": "איך עובדת מקדמה?",
    "delivery.faq4a":
      "מקדמה שומרת את ההזמנה ואת זמן המשלוח, במיוחד בתאריכים מבוקשים. נשלח פרטים לאחר ההזמנה.",
    "contacts.title": "יצירת קשר",
    "contacts.description":
      "צרו איתנו קשר בדרך שנוחה לכם. בדרך כלל אנחנו עונים מהר.",
    "contacts.phoneNote": "WhatsApp / שיחות",
    "contacts.emailNote": "להזמנות ושאלות",
    "contacts.location": "מיקום",
    "contacts.locationValue": "מוסקבה, רוסיה",
    "contacts.pickupNote": "איסוף עצמי בתיאום מראש",
    "contacts.hours": "שעות פעילות",
    "contacts.weekdays": "ב׳-ו׳: 10:00-19:00",
    "contacts.weekend": "ש׳-א׳: 11:00-16:00",
    "contacts.howToOrder": "איך מזמינים",
    "contacts.orderStep1": "כתבו לנו ב-WhatsApp / Telegram או באימייל.",
    "contacts.orderStep2": "ציינו תאריך, סוג מארז, תקציב והעדפות שוקולד.",
    "contacts.orderStep3": "נאשר פרטים וזמן איסוף/משלוח.",
    "contacts.fastContact": "קשר מהיר",
    "contacts.fastContactText": "בחרו ערוץ נוח, אנחנו עונים במהלך היום.",
    "contacts.map": "מפה",
    "contacts.mapText":
      "מוסקבה והאזור. כתובת מדויקת והוראות הגעה נשלח לאחר אישור ההזמנה.",
    "contacts.route": "מפת הגעה",
    "privacy.back": "חזרה לקטלוג",
    "privacy.title": "מדיניות עיבוד נתונים אישיים",
    "privacy.updated": "תאריך עדכון:",
    "privacy.date": "20 ביוני 2026",
    "privacy.intro":
      "מדיניות זו מתארת אילו נתונים אישיים עשויים להיות מעובדים באתר Candy Craft ולאילו מטרות הם משמשים.",
    "privacy.section1": "1. אילו נתונים מעובדים",
    "privacy.section1Text": "האתר עשוי לעבד את הנתונים הבאים:",
    "privacy.itemName": "שם פרטי ושם משפחה;",
    "privacy.itemPhone": "מספר טלפון;",
    "privacy.itemAddress": "כתובת משלוח;",
    "privacy.itemOrder": "הרכב ההזמנה והערות להזמנה;",
    "privacy.itemTech": "נתונים טכניים הנדרשים להפעלת האתר.",
    "privacy.section2": "2. מטרות העיבוד",
    "privacy.section2Text": "הנתונים משמשים ל:",
    "privacy.purposeAuth": "רישום והתחברות משתמשים;",
    "privacy.purposeOrders": "ביצוע וטיפול בהזמנות;",
    "privacy.purposeContact": "יצירת קשר עם המשתמש לגבי הזמנה או פנייה;",
    "privacy.purposeCart": "תפעול העגלה והאזור האישי;",
    "privacy.purposeSecurity": "שמירה על אבטחת האתר.",
    "privacy.section3": "3. העברת נתונים לצדדים שלישיים",
    "privacy.section3Text":
      "נתונים עשויים להימסר רק כאשר הדבר נדרש להפעלת האתר ולביצוע ההזמנה, למשל לספק תשלום או שירות משלוחים. הנתונים אינם נמכרים ואינם נמסרים לפרסום חיצוני.",
    "privacy.section4": "4. Cookies",
    "privacy.section4Text":
      "האתר משתמש בעוגיות ובמנגנונים טכניים דומים לצורך התחברות, שמירת סשן, תפעול העגלה ואבטחה.",
    "privacy.section5": "5. שמירה והגנה על נתונים",
    "privacy.section5Text":
      "הנתונים נשמרים במערכת המידע של האתר ומשמשים רק במידה הנדרשת להפעלת השירות. סיסמאות משתמשים אינן נשמרות כטקסט גלוי.",
    "privacy.section6": "6. זכויות המשתמש",
    "privacy.section6Text": "המשתמש יכול לבקש:",
    "privacy.rightsClarify": "עדכון או הבהרת הנתונים שלו;",
    "privacy.rightsDelete": "מחיקת חשבון או נתונים מסוימים;",
    "privacy.rightsInfo": "מידע על מטרות עיבוד הנתונים.",
    "privacy.section7": "7. יצירת קשר",
    "privacy.section7Text": "לשאלות בנושא עיבוד נתונים אישיים אפשר לכתוב ל:",
    "privacy.continue": "המשך קניות",
    "privacy.emailCta": "כתיבה באימייל",
    "productPage.loading": "טוען מוצר...",
    "productPage.notFound": "המוצר לא נמצא",
    "productPage.notFoundDescription": "מצטערים, המוצר המבוקש לא קיים או הוסר",
    "productPage.backCatalog": "חזרה לקטלוג",
    "productPage.home": "ראשי",
    "productPage.back": "→ חזרה",
    "productInfo.pieces": "יח׳",
    "productInfo.total": "סה״כ:",
    "productInfo.add": "הוספה לעגלה",
    "productInfo.categoryLabel": "קטגוריה:",
    "productInfo.categoryValue": "עוגות ממתקים",
    "productInfo.weightLabel": "משקל:",
    "productInfo.weightValue": "מותאם אישית לפי הרכב",
    "productInfo.compositionLabel": "הרכב:",
    "productInfo.compositionValue": "ממתקים, שוקולד, אריזה ובסיס דקורטיבי",
    "cart.title": "עגלת קניות",
    "cart.emptyTitle": "העגלה ריקה",
    "cart.emptyDescription": "הוסיפו מוצרים מהקטלוג כדי להתחיל קנייה",
    "cart.catalogCta": "מעבר לקטלוג",
    "cart.customBuild": "הרכבה אישית",
    "cart.available": "זמין",
    "cart.innerMissing": "שכבה פנימית לא צוינה",
    "cart.noDecor": "ללא קישוט",
    "cart.inscription": "כיתוב",
    "cart.candies": "ממתקים",
    "cart.decrease": "הפחתה",
    "cart.increase": "הגדלה",
    "cart.remove": "הסרת מוצר",
    "cart.summaryTitle": "סיכום הזמנה",
    "cart.items": "מוצרים",
    "cart.discount": "הנחה",
    "cart.payTotal": "סה״כ לתשלום",
    "cart.checkout": "השלמת הזמנה",
    "cart.freeDelivery": "משלוח חינם מעל 6000 ₽",
    "cart.shape.round": "עגול",
    "cart.shape.square": "מרובע",
    "cart.shape.heart": "לב",
    "cart.size.small": "קטן",
    "cart.size.medium": "בינוני",
    "cart.size.large": "גדול",
    "cart.color.pink": "ורוד",
    "cart.color.gold": "זהב",
    "cart.color.white": "לבן",
    "cart.decor.none": "ללא קישוט",
    "cart.decor.flowers": "פרחים",
    "cart.decor.bow": "סרט",
    "cart.decor.topper": "טופר עם כיתוב",
    "cart.packaging.standard": "קופסה ממותגת",
    "cart.packaging.window": "קופסה עם חלון",
    "cart.packaging.gift": "אריזת מתנה",
    "cart.packaging.premium": "קופסת פרימיום",
    "auth.shellAccount": "חשבון מתוק",
    "auth.benefitFast": "✅ הזמנה מהירה",
    "auth.benefitHistory": "✅ היסטוריית קניות מתוקה",
    "auth.benefitRepeat": "✅ הזמנה חוזרת בלחיצה אחת",
    "auth.tagline": "Candy Craft — עוגות מהשוקולדים האהובים.",
    "auth.emailInvalid": "אימייל לא תקין",
    "auth.passwordRequired": "יש להזין סיסמה",
    "auth.passwordMin": "לפחות 6 תווים",
    "auth.loginFallback": "לא הצלחנו להתחבר",
    "auth.loginTitle": "ברוכים השבים",
    "auth.loginSubtitle": "התחברו כדי להזמין מהר יותר ולעקוב אחרי משלוחים.",
    "auth.noAccount": "אין חשבון?",
    "auth.registerLink": "הרשמה",
    "auth.google": "כניסה עם Google",
    "auth.yandex": "כניסה עם Yandex",
    "auth.vk": "כניסה עם VK",
    "auth.emailPlaceholder": "לאן לשלוח קבלה",
    "auth.password": "סיסמה",
    "auth.forgot": "שכחתם סיסמה?",
    "auth.passwordPlaceholder": "המרכיב הסודי",
    "auth.hide": "הסתר",
    "auth.show": "הצג",
    "auth.loginButton": "כניסה",
    "auth.loggingIn": "מתחבר...",
    "auth.lastNameRequired": "יש להזין שם משפחה",
    "auth.confirmPasswordRequired": "יש לחזור על הסיסמה",
    "auth.passwordMismatch": "הסיסמאות אינן תואמות",
    "auth.accountCreated": "החשבון נוצר. עכשיו אפשר להתחבר.",
    "auth.registerFallback": "לא הצלחנו להירשם",
    "auth.registerTitle": "בואו ניצור חשבון",
    "auth.registerSubtitle": "כמה שניות ופרופיל Candy Craft שלכם מוכן.",
    "auth.hasAccount": "כבר יש חשבון?",
    "auth.firstName": "שם פרטי",
    "auth.firstNamePlaceholder": "איך לפנות אליכם",
    "auth.lastName": "שם משפחה",
    "auth.lastNamePlaceholder": "למשלוח",
    "auth.phone": "טלפון",
    "auth.optional": "(אופציונלי)",
    "auth.confirmPassword": "חזרה על הסיסמה",
    "auth.confirmPasswordPlaceholder": "עוד פעם ליתר ביטחון",
    "auth.consentStart": "אני מסכים/ה לעיבוד נתונים אישיים וקראתי את",
    "auth.registerButton": "הרשמה",
    "auth.registering": "יוצר חשבון...",
    "account.loadProfileError": "לא הצלחנו לטעון את הפרופיל",
    "account.loadOrdersError": "לא הצלחנו לטעון הזמנות",
    "account.fillName": "מלאו שם פרטי ושם משפחה",
    "account.checkEmail": "בדקו את האימייל",
    "account.phoneFormat": "הזינו טלפון בפורמט ‎+7 (999) 999-99-99",
    "account.saved": "נשמר",
    "account.saveError": "לא הצלחנו לשמור",
    "account.title": "אזור אישי",
    "account.helloPrefix": "שלום,",
    "account.helloSuffix": "כאן נמצאים הפרופיל וההזמנות שלך.",
    "account.admin": "לאדמין",
    "account.logout": "יציאה",
    "account.profile": "פרופיל",
    "account.orders": "הזמנות",
    "account.profileData": "פרטי פרופיל",
    "account.profileHint": "עדכנו פרטי קשר להתראות על הזמנות",
    "account.phoneRu": "טלפון (רוסיה)",
    "account.phoneRequired": "נדרש ליצירת קשר לגבי ההזמנה.",
    "account.saving": "שומר...",
    "account.save": "שמירה",
    "account.myOrders": "ההזמנות שלי",
    "account.newOrder": "הזמנה חדשה",
    "account.noOrders": "עדיין אין הזמנות. זמן טוב להרכיב יצירה מתוקה",
    "account.number": "מס׳",
    "account.date": "תאריך",
    "account.status": "סטטוס",
    "account.amount": "סכום",
    "account.detailsSoon": "פרטים בקרוב",
    "account.statusAuto": "הסטטוסים מתעדכנים אוטומטית כשההזמנה מתקדמת.",
    "account.status.PENDING": "נוצר",
    "account.status.PAID": "שולם",
    "account.status.PROCESSING": "בהכנה",
    "account.status.SHIPPED": "נשלח",
    "account.status.COMPLETED": "הושלם",
    "account.status.CANCELED": "בוטל",
    "checkout.selectDelivery": "בחרו שיטת משלוח",
    "checkout.loginRequired": "צריך להתחבר לחשבון לפני תשלום",
    "checkout.emptyCart": "העגלה ריקה",
    "checkout.paymentLinkMissing": "התשלום נוצר, אך לא התקבל קישור לתשלום",
    "checkout.createError": "לא הצלחנו ליצור הזמנה/תשלום",
    "checkout.successTitle": "🎉 ההזמנה נוצרה!",
    "checkout.successText": "קופסת הממתקים הקסומה שלכם כבר בהרכבה!",
    "checkout.orderNumber": "מספר הזמנה:",
    "checkout.courierCall": "השליח יתקשר אליכם בתוך 30 דקות",
    "checkout.delivery": "משלוח",
    "checkout.assembly": "הרכבה",
    "checkout.assemblyNow": "מתחילה עכשיו",
    "checkout.sms": "הודעת SMS",
    "checkout.sentTo": "נשלח אל",
    "checkout.backShop": "חזרה לחנות",
    "checkout.backCart": "חזרה לעגלה",
    "checkout.title": "השלמת הזמנה",
    "checkout.step": "שלב",
    "checkout.of": "מתוך",
    "checkout.step1": "פרטי קשר",
    "checkout.step2": "שיטת משלוח",
    "checkout.step3": "אפשרויות נוספות",
    "checkout.step4": "אישור",
    "checkout.productsCount": "מוצרים",
    "checkout.back": "חזרה",
    "checkout.continue": "המשך",
    "checkout.consentStart":
      "אני מסכים/ה לעיבוד נתונים אישיים לצורך ביצוע ההזמנה וקראתי את",
    "checkout.processing": "מבצע הזמנה...",
    "checkout.finish": "סיום הזמנה",
    "checkout.total": "סה״כ:",
    "checkout.addressTitle": "כתובת משלוח",
    "checkout.addressSubtitle": "ספרו לנו לאן לשלוח את המתוקים",
    "checkout.savedAddresses": "כתובות שמורות",
    "checkout.selectAddress": "בחרו כתובת",
    "checkout.address": "כתובת",
    "checkout.deliveryMethodTitle": "שיטת משלוח",
    "checkout.deliveryMethodSubtitle": "כמה מהר תרצו לקבל את המתוקים?",
    "checkout.deliveryLoadError": "לא הצלחנו לטעון שיטות משלוח",
    "checkout.optionsTitle": "אפשרויות נוספות",
    "checkout.optionsSubtitle": "הוסיפו קסם לקופסת הממתקים שלכם",
    "checkout.optionsLoadError": "לא הצלחנו לטעון אפשרויות נוספות",
    "checkout.noteLabel": "בקשות להזמנה",
    "checkout.notePlaceholder": "כתבו בקשות, אלרגיות או הוראות מיוחדות...",
    "checkout.reviewTitle": "בדקו את ההזמנה",
    "checkout.reviewSubtitle": "ודאו שהכול נכון לפני השלמה",
    "checkout.yourBox": "🍬 קופסת הממתקים שלכם 🍬",
    "checkout.orderContents": "תכולת ההזמנה",
    "checkout.customCake": "עוגה אישית",
    "checkout.customCandyCake": "עוגת ממתקים אישית",
    "checkout.extraOptions": "אפשרויות נוספות:",
    "checkout.summary": "סיכום הזמנה",
    "checkout.products": "מוצרים:",
    "payment.status.SUCCEEDED": "התשלום עבר בהצלחה",
    "payment.status.PENDING": "התשלום נוצר",
    "payment.status.WAITING_FOR_CAPTURE": "התשלום ממתין לאישור",
    "payment.status.CANCELED": "התשלום בוטל",
    "payment.status.FAILED": "שגיאת תשלום",
    "payment.invalidOrder": "מספר הזמנה לא תקין",
    "payment.loadError": "לא הצלחנו לקבל סטטוס תשלום",
    "payment.title": "תוצאת תשלום",
    "payment.checking": "בודק סטטוס...",
    "payment.order": "הזמנה:",
    "payment.amount": "סכום:",
    "payment.statusLabel": "סטטוס:",
    "payment.notFound": "עדיין לא נמצא תשלום להזמנה",
    "payment.account": "לאזור האישי",
    "payment.catalog": "לקטלוג",
    "address.placeholder": "עיר, רחוב, בית",
    "address.searching": "מחפש כתובת...",
    "cake.backCatalog": "חזרה לקטלוג",
    "cake.badge": "בונה בשלבים",
    "cake.heroTitle": "הרכיבו עוגה לפי שלבים",
    "cake.heroText":
      "קודם בוחרים גודל וצורה, אחר כך שורת ממתקים חיצונית, שכבה פנימית, קישוט ואריזה. המחיר מתעדכן בכל שלב.",
    "cake.stepSize": "גודל",
    "cake.stepSizeCaption": "צורה ומידות העוגה",
    "cake.stepOuter": "שורה חיצונית",
    "cake.stepOuterCaption": "ממתקים בצדדים וצבע סרט",
    "cake.stepInner": "שכבה פנימית",
    "cake.stepInnerCaption": "ממתקים בתוך ההרכבה",
    "cake.stepDecor": "קישוט",
    "cake.stepDecorCaption": "פרטים וכיתוב",
    "cake.stepPackaging": "אריזה",
    "cake.stepPackagingCaption": "הגשה סופית",
    "cake.loginRequired": "התחברו כדי להוסיף עוגה לעגלה",
    "cake.addError": "לא הצלחנו להוסיף את העוגה לעגלה",
    "cake.chooseSize": "בחרו גודל",
    "cake.chooseShape": "בחרו צורה",
    "cake.outerCandies": "שורת ממתקים חיצונית",
    "cake.ribbonColor": "צבע סרט והדגשות",
    "cake.inscription": "כיתוב",
    "cake.inscriptionPlaceholder": "לדוגמה: יום הולדת שמח",
    "cake.inscriptionHint": "עד 40 תווים, הכיתוב ייכנס לעיצוב ולהזמנה.",
    "cake.stage": "שלב",
    "cake.checkSummary": "בדקו את הסיכום והכמות בצד.",
    "cake.next": "המשך",
    "cake.summaryStep": "שלב 5",
    "cake.summaryTitle": "סיכום",
    "cake.shape": "צורה",
    "cake.notSet": "לא הוגדר",
    "cake.color": "צבע",
    "cake.quantity": "כמות",
    "cake.adding": "מוסיף...",
    "cake.addToCart": "הוספה לעגלה",
    "cake.selectedCandies": "ממתקים נבחרים ואחוזים",
    "cake.pickCandy": "בחרו לפחות ממתק אחד.",
    "cake.percentSum": "סכום האחוזים",
    "cake.percentError":
      "סכום האחוזים חייב להיות בדיוק 100%. אחרת אי אפשר להמשיך.",
    "cake.innerLayerPrice": "עלות השכבה הפנימית",
    "cake.compositionEmpty": "ההרכב עדיין לא הוגדר.",
    "cake.innerPriceHint": "העלות מחושבת לפי האחוזים שנבחרו וגודל העוגה.",
    "cake.option.base.round.label": "עוגה עגולה",
    "cake.option.base.round.description": "צורה קלאסית",
    "cake.option.base.heart.label": "לב",
    "cake.option.base.heart.description": "הדגשה למתנה",
    "cake.option.base.square.label": "עוגה מרובעת",
    "cake.option.base.square.description": "צורה מודרנית וישרה",
    "cake.option.color.pink.label": "ורוד",
    "cake.option.color.gold.label": "זהב",
    "cake.option.color.white.label": "לבן",
    "cake.option.wrapper.satin.label": "סרט סאטן",
    "cake.option.wrapper.satin.description": "סרט קלאסי סביב העוגה",
    "cake.option.wrapper.lace.label": "עטיפת תחרה",
    "cake.option.wrapper.lace.description": "גימור עדין ומרקמי בצדדים",
    "cake.option.wrapper.kraft.label": "שול קראפט",
    "cake.option.wrapper.kraft.description": "הגשה טבעית ורגועה",
    "cake.option.wrapper.transparent.label": "שול שקוף",
    "cake.option.wrapper.transparent.description": "מבליט את הממתקים הגלויים",
    "cake.option.packaging.standard.label": "קופסה ממותגת",
    "cake.option.packaging.standard.description": "קופסת CandyCraft לבנה",
    "cake.option.packaging.window.label": "קופסה עם חלון",
    "cake.option.packaging.window.description": "רואים את העוגה לפני הפתיחה",
    "cake.option.packaging.gift.label": "אריזת מתנה",
    "cake.option.packaging.gift.description": "סרט, תגית והגשה חגיגית",
    "cake.option.decor.bow.label": "סרט",
    "cake.option.decor.bow.description": "סרט דקורטיבי על העוגה",
    "cake.option.decor.topper.label": "טופר עם כיתוב",
    "cake.option.decor.topper.description": "טופר עליון עם הטקסט שלכם",
    "cake.noDecor": "ללא קישוט",
  },
};

type LanguageContextValue = {
  language: Language;
  isHebrew: boolean;
  toggleLanguage: () => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === "undefined") return "ru";
    return window.localStorage.getItem("candycraft-language") === "he"
      ? "he"
      : "ru";
  });

  const isHebrew = language === "he";

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = isHebrew ? "rtl" : "ltr";
    window.localStorage.setItem("candycraft-language", language);
  }, [isHebrew, language]);

  const toggleLanguage = useCallback(() => {
    setLanguage((current) => (current === "ru" ? "he" : "ru"));
  }, []);

  const t = useCallback(
    (key: TranslationKey) => dictionaries[language][key] ?? key,
    [language],
  );

  const value = useMemo(
    () => ({ language, isHebrew, toggleLanguage, t }),
    [isHebrew, language, t, toggleLanguage],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
